### ISSUE TITLE
This app was never built... that's lame

### ISSUE THREAD

**Issue by gbreen12** [heatonandy/scripturepower#1]
See title

**Comment by heatonandy** [comment]
This is an issue I think we better fix at some point in the near future. I am building momentum slowly in how much time I spend and what I'm learning with Xamarin, so I'm hoping that day is not too far in the future. I just made a login/register page with Xamarin that doesn't look terrible!
![2017-03-10 14 13 22](https://cloud.githubusercontent.com/assets/3374523/23798344/3b73c31e-0572-11e7-8400-242841b2ecc5.png)
